### ISSUE TITLE
Error after exiting the app

### ISSUE THREAD

**Issue by rowbotman** [likeblood/SmartMed#4]
After pressing button `Завершить` I saw this error:  
```txt
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Desktop\HSE\Projects\SmartMed\SmartMedApp\backend\ModuleManipulator.py", line 26, in start
    module.run()
  File "D:\Desktop\HSE\Projects\SmartMed\SmartMedApp\logs\logger.py", line 14, in wrapper
    result = fn(*args, **kwargs)
  File "D:\Desktop\HSE\Projects\SmartMed\SmartMedApp\backend\modules\ModuleInterface.py", line 63, in run
    self.start()
  File "D:\Desktop\HSE\Projects\SmartMed\SmartMedApp\logs\logger.py", line 14, in wrapper
    result = fn(*args, **kwargs)
  File "D:\Desktop\HSE\Projects\SmartMed\SmartMedApp\backend\modules\dash\Dashboard.py", line 50, in start
    self.app.layout = self._generate_layout()
  File "D:\Desktop\HSE\Projects\SmartMed\SmartMedApp\backend\modules\dash\PredictionDashboard.py", line 34, in _generate_layout
    if self.settings['model'] == 'linreg':
KeyError: 'model'
```

**Comment by rowbotman** [comment]
Nope, it's my fault. I broke something in the code
